-- 1. Create clientes table
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  rut TEXT,
  telefono TEXT,
  correo TEXT,
  direccion TEXT,
  observaciones TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create movimientos table
CREATE TABLE IF NOT EXISTS movimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  fecha DATE NOT NULL,
  detalle TEXT NOT NULL,
  banco TEXT,
  boleta TEXT,
  credito INTEGER DEFAULT 0,
  abono INTEGER DEFAULT 0,
  registrado BOOLEAN DEFAULT false,
  pagado BOOLEAN DEFAULT false,
  fecha_registrado DATE,
  fecha_pagado DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_movimientos_id_cliente ON movimientos(id_cliente);
CREATE INDEX IF NOT EXISTS idx_clientes_nombre ON clientes(nombre);

-- 4. Enable Row Level Security (RLS)
-- For simplicity, since the app will have authentication, we enable RLS 
-- and require users to be authenticated to perform any action.
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos ENABLE ROW LEVEL SECURITY;

-- 5. Create policies for authenticated users
CREATE POLICY "Allow all operations for authenticated users on clientes"
  ON clientes
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow all operations for authenticated users on movimientos"
  ON movimientos
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- 6. Create clientes_resumen view for dashboard aggregations
CREATE OR REPLACE VIEW clientes_resumen AS
SELECT c.id,
       c.nombre,
       c.rut,
       c.telefono,
       c.correo,
       c.direccion,
       c.observaciones,
       c.created_at,
       COALESCE(SUM(m.credito), 0)::BIGINT AS debe,
       COALESCE(SUM(m.abono), 0)::BIGINT AS haber,
       (COALESCE(SUM(m.credito), 0) - COALESCE(SUM(m.abono), 0))::BIGINT AS saldo
FROM clientes c
LEFT JOIN movimientos m ON c.id = m.id_cliente
GROUP BY c.id, c.nombre, c.rut, c.telefono, c.correo, c.direccion, c.observaciones, c.created_at;

